language: android
android:
  components:
    #this does not actually install, hence the before_install code below
    - extra-android-m2repository

    # The BuildTools version used by your project
    - build-tools-23.0.1
    # The SDK version used to compile your project
    - android-23
before_install:
  # Installs the android m2 repo, remove if the above starts working
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
  # Fixes a permission bug
  - chmod +x gradlew
jdk:
  - oraclejdk7
branches:
  only:
  - master
  - develop
  
